apiVersion: v1
kind: Namespace
metadata:
  name: k8s-datadog-newbie
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangogirls
  namespace: k8s-datadog-newbie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: djangogirls
  template:
    metadata:
      labels:
        app: djangogirls
    spec:
      containers:
        - image: yktakaha4/djangogirls:latest
          imagePullPolicy: Always
          name: djangogirls
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              value: djangogirls
            - name: POSTGRES_PASSWORD
              value: k8s-datadog-newbie
          command:
            - "./djangogirls_entrypoint.bash"
        - image: postgres:9.6.23
          imagePullPolicy: Always
          name: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: djangogirls
            - name: POSTGRES_USER
              value: djangogirls
            - name: POSTGRES_PASSWORD
              value: k8s-datadog-newbie
---
apiVersion: v1
kind: Service
metadata:
  name: djangogirls
  namespace: k8s-datadog-newbie
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: djangogirls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: djangogirls
  namespace: k8s-datadog-newbie
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: djangogirls
                port:
                  number: 80
